FROM node:18-alpine

WORKDIR /opt/app
RUN yarn global add pm2
EXPOSE 3000

WORKDIR /nestjs-dockerized-api

COPY ./api/package.json .

RUN yarn

COPY ./api/. .

RUN yarn build

CMD ["pm2-runtime", "start", "yarn", "--name", "nestjs-dockerized-api", "--interpreter", "sh", "--", "start"]